version: '3.8'

services: 
  exert-mysql80-server:
    image: mysql:8.0.26
    container_name: exert-mysql-server
    restart: always
    ports: 
      - '3306:3306'
      - '33060:33060'
    volumes: 
      - ./docker/data/:/var/lib/mysql
      - ./docker/file/:/var/lib/mysql-files
      - ./docker/config/:/etc/mysql/:ro
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=exert
    networks: 
      - exert-mysql-net
    security_opt:
      # 特权容器无限制，不然报没权限。
      - seccomp:unconfined

  exert-mysql56-server:
    image: mysql/mysql-server:5.6.51
    container_name: exert-mysql56-server
    restart: always
    ports: 
      - '3307:3306'
      - '33070:33060'
    volumes: 
      - ./docker/data56/:/var/lib/mysql
      - ./docker/file56/:/var/lib/mysql-files
      # - ./docker/conf56/my.cnf:/etc/my.cnf:ro
    # environment:
    #   - MYSQL_ROOT_PASSWORD=password
    #   - MYSQL_DATABASE=exert
    #   - MYSQL_HOST=%
    networks: 
      - exert-mysql-net

  exert-mysql55-server:
    image: mysql/mysql-server:5.5.62
    container_name: exert-mysql55-server
    restart: always
    ports: 
      - '3308:3306'
      - '33080:33060'
    volumes: 
      - ./docker/data55/:/var/lib/mysql
      - ./docker/file55/:/var/lib/mysql-files
      - ./docker/conf55/my.cnf:/etc/my.cnf
    # environment:
    #   - MYSQL_ROOT_PASSWORD=password
    #   - MYSQL_DATABASE=exert
    #   - MYSQL_HOST=%
    # 这 5.5 很不适合 docker 很多都要手动操作，最后通过 --skip-grant-tables 跳过权限认证。。
    # 首次登录 mysql 必须设置权限，不然下次登录就开始验证，只能通过 mysql 交互式接口，无法通过 mysql -e 传递命令，这样很不 docker 。
    command: >
      bash -c "chmod 644 /etc/my.cnf && /entrypoint.sh mysqld --skip-grant-tables"
    networks: 
      - exert-mysql-net

networks: 
  exert-mysql-net:
    name: exert-mysql-net
    driver: bridge
