version: '3.8'

services: 
  exert-mysql-server:
    image: mysql:8.0.26
    container_name: exert-mysql-server
    restart: always
    ports: 
      - '3306:3306'
      - '33060:33060'
    volumes: 
      - ./docker/data/:/var/lib/mysql
      - ./docker/file/:/var/lib/mysql-files
      - ./docker/config/:/etc/mysql/:ro
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=exert
    networks: 
      - exert-mysql-net
    security_opt:
      # 特权容器无限制，不然报没权限。
      - seccomp:unconfined

  exert-mysql56-server:
    image: mysql/mysql-server:5.6.51
    container_name: exert-mysql56-server
    restart: always
    ports: 
      - '3307:3306'
      - '33070:33060'
    volumes: 
      - ./docker/data56/:/var/lib/mysql
      - ./docker/file56/:/var/lib/mysql-files
      #- ./docker/config/:/etc/mysql/:ro
    # environment:
    #   - MYSQL_ROOT_PASSWORD=password
    #   - MYSQL_DATABASE=exert
    #   - MYSQL_HOST=%
    networks: 
      - exert-mysql-net

networks: 
  exert-mysql-net:
    name: exert-mysql-net
    driver: bridge
